//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_RESOURCE_TYPE
    {
        public RISK_RESOURCE_TYPE()
        {
            this.RISK_RESOURCE = new HashSet<RISK_RESOURCE>();
        }
    
        public long AUTO_ID { get; set; }
        public string RESOURCE_TYPE_NAME { get; set; }
        public string RESOURCE_TYPE_DESCRIPTION { get; set; }
    
        public virtual ICollection<RISK_RESOURCE> RISK_RESOURCE { get; set; }
    }
}
