//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_PROJECT
    {
        public RISK_PROJECT()
        {
            this.RISK_TASK = new HashSet<RISK_TASK>();
            this.RISK_PROJECT_RES_ASSIGNMENT = new HashSet<RISK_PROJECT_RES_ASSIGNMENT>();
        }
    
        public long PRJ_ID { get; set; }
        public string PRJ_NAME { get; set; }
        public string PRJ_DESCRIBE { get; set; }
        public Nullable<System.DateTime> PRJ_DATE { get; set; }
        public byte[] PRJ_XML { get; set; }
    
        public virtual ICollection<RISK_TASK> RISK_TASK { get; set; }
        public virtual ICollection<RISK_PROJECT_RES_ASSIGNMENT> RISK_PROJECT_RES_ASSIGNMENT { get; set; }
    }
}
