//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_TASK
    {
        public RISK_TASK()
        {
            this.RISK_TASK_RESOURCE_ASSIGNMENT = new HashSet<RISK_TASK_RESOURCE_ASSIGNMENT>();
        }
    
        public long AUTO_ID { get; set; }
        public long TASK_ID { get; set; }
        public string TASK_WBS { get; set; }
        public string TASK_NAME { get; set; }
        public long TASK_PROJECT_ID { get; set; }
        public Nullable<short> TASK_IS_SUMMARY { get; set; }
        public Nullable<long> TASK_NESTED_PARENT_ID { get; set; }
        public Nullable<long> TASK_PRIORITY { get; set; }
        public Nullable<long> TASK_EXPRESSION_ID { get; set; }
        public Nullable<long> TASK_LEVEL { get; set; }
    
        public virtual RISK_PROJECT RISK_PROJECT { get; set; }
        public virtual ICollection<RISK_TASK_RESOURCE_ASSIGNMENT> RISK_TASK_RESOURCE_ASSIGNMENT { get; set; }
    }
}
