//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_LINK_TYPE
    {
        public long AUTO_ID { get; set; }
        public string LINK_NAME { get; set; }
        public string LINK_DESCRIPTION { get; set; }
    }
}
