//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_TASK_INSTANCE
    {
        public long AUTO_ID { get; set; }
        public long TASK_AUTO_ID { get; set; }
        public long PRJ_ID { get; set; }
        public Nullable<short> TASK_IS_CRITICAL { get; set; }
        public Nullable<decimal> TASK_ACTUAL_DUR_PERIOD { get; set; }
        public Nullable<decimal> TASK_VE { get; set; }
        public Nullable<decimal> TASK_VL { get; set; }
        public Nullable<long> SIM_SEQUENCE { get; set; }
        public Nullable<long> SIM_VERSION { get; set; }
        public Nullable<decimal> START_TIME { get; set; }
    
        public virtual RISK_PRJ_VERSION_INFO RISK_PRJ_VERSION_INFO { get; set; }
        public virtual RISK_TASK_INSTANCE_RES RISK_TASK_INSTANCE_RES { get; set; }
    }
}
