//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_LINK
    {
        public long AUTO_ID { get; set; }
        public long PRJ_ID { get; set; }
        public long TASK_PRE_ID { get; set; }
        public long TASK_SUC_ID { get; set; }
        public long LINK_TYPE { get; set; }
        public Nullable<long> DELAY_DAYS { get; set; }
    }
}
