//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISK_TASK_INSTANCE_RES
    {
        public long TASK_INSTANCE_ID { get; set; }
        public Nullable<long> TASK_AUTO_ID { get; set; }
        public Nullable<long> RESOURCE_ID { get; set; }
        public Nullable<decimal> WAIT_TIME { get; set; }
    
        public virtual RISK_TASK_INSTANCE RISK_TASK_INSTANCE { get; set; }
    }
}
